index:
   path: /home
   controller: App\Controller\HomeController::index

animales:
   path: /animales/{nombre}/{apellidos}
   controller: App\Controller\HomeController::animales
   defaults: {nombre: 'Gemma', apellidos: 'Gomez Robledo'}
   methods: [GET]
   requirements:
       nombre: '[a-zA-Z]+'
       apellidos: '[0-9]+'

redirigir:
   path: /redirigir
   controller: App\Controller\HomeController::redirigir

